global:
  scrape_interval: 15s

scrape_configs:
  # Забираем метрики у самого Prometheus
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  # Добавляем задание на сбор метрик с node_exporter
  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node_exporter:9100']
